/*
* This file was generated by the Gradle 'init' task.
*/

plugins {
  `java-library`
}
dependencies {
  api(project(":daisy-core"))
  api("com.google.code.gson:gson:2.10.1")
  compileOnly("org.spigotc:spigot-api:1.8.8-R0.1-SNAPSHOT")
}

description = "Json reader implemented with Gson"
