/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  `java-library`
}

dependencies {
  api(project(":daisy-core"))
  compileOnly("org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT")
}

description = "Daisy demo plugin"